/* DATABASE: DB_EXPEND_LIST
 * DESCRITION: BASIC STRUCTURE USE IN THE DATABASE [DB_EXPEND_LIST].
 */
/************************************************************************/
DROP USER IF EXISTS 'DB_EXPEND_LIST'@'localhost';
DROP DATABASE IF EXISTS `DB_EXPEND_LIST`;
/************************************************************************/
CREATE USER IF NOT EXISTS 'DB_EXPEND_LIST'@'localhost' IDENTIFIED BY 'DB_EXPEND_LIST';
/************************************************************************/
CREATE DATABASE IF NOT EXISTS `DB_EXPEND_LIST` DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci;
USE `DB_EXPEND_LIST`;
/************************************************************************/
REVOKE ALL PRIVILEGES ON *.* FROM `DB_EXPEND_LIST`@`Localhost`;
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO `DB_EXPEND_LIST`@`Localhost`;
/************************************************************************/

CREATE TABLE TB_LOCAL(
    ID INT(11) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_PERSON(
    ID INT(11) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    USER TEXT NOT NULL,
    PASS VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(255),
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_DEFINITION(
    ID INT(11) UNIQUE NOT NULL,
    ID_LOCAL INT(11) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    DATE_INI DATE,
    DATE_END DATE,
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_EXPENSE(
	ID INT(11) UNIQUE NOT NULL,
    ID_DEFINITION INT(11) NOT NULL,
    ID_PERSON INT(11) NOT NULL,
    ID_TYPE INT(11) NOT NULL,
    NOTE TEXT,
    DATE_INCLUDE DATE NOT NULL,
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_TYPE(
    ID INT(11) NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_ITEM(
    ID INT(11) UNIQUE NOT NULL,
    ID_KEYWORD INT(11) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_KEYWORD(
    ID INT(11) UNIQUE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRIMARY KEY(ID)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

CREATE TABLE TB_EXPENSE_ITEM(
    ID_EXPENSE INT(11) NOT NULL,
    ID_ITEM INT(11) NOT NULL,
    PRICE DECIMAL(5,2),
    PRIMARY KEY(ID_EXPENSE,ID_ITEM)
)CHARACTER SET Latin1 COLLATE latin1_general_ci;

/******************************************************************************/
/* FOREIGN KEYS */
ALTER TABLE TB_DEFINITION ADD CONSTRAINT FK_TB_LOCAL_TB_DEFINITION FOREIGN KEY (ID_LOCAL) REFERENCES TB_LOCAL(ID) ON UPDATE CASCADE;

ALTER TABLE TB_ITEM ADD CONSTRAINT FK_TB_KEYWORD_TB_ITEM FOREIGN KEY (ID_KEYWORD) REFERENCES TB_KEYWORD(ID) ON UPDATE CASCADE;

ALTER TABLE TB_EXPENSE_ITEM ADD CONSTRAINT FK_TB_ITEM_TB_EXPENSE_ITEM FOREIGN KEY (ID_ITEM) REFERENCES TB_ITEM(ID) ON UPDATE CASCADE;
ALTER TABLE TB_EXPENSE_ITEM ADD CONSTRAINT FK_TB_EXPENSE_TB_EXPENSE_ITEM FOREIGN KEY (ID_EXPENSE) REFERENCES TB_EXPENSE(ID) ON UPDATE CASCADE;

ALTER TABLE TB_EXPENSE ADD CONSTRAINT FK_TB_DEFINITION_TB_EXPENSE FOREIGN KEY (ID_DEFINITION) REFERENCES TB_DEFINITION(ID) ON UPDATE CASCADE;
ALTER TABLE TB_EXPENSE ADD CONSTRAINT FK_TB_TYPE_TB_EXPENSE FOREIGN KEY (ID_TYPE) REFERENCES TB_TYPE(ID) ON UPDATE CASCADE;
ALTER TABLE TB_EXPENSE ADD CONSTRAINT FK_TB_PERSON_TB_EXPENSE FOREIGN KEY (ID_PERSON) REFERENCES TB_PERSON(ID) ON UPDATE CASCADE;
